#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
source ~/python-2.6/virtenv/bin/activate
cd $OPENSHIFT_REPO_DIR/wsgi/osqa
python manage.py syncdb --all --no
python manage.py migrate forum --fake
